using Microsoft.VisualStudio.TestTools.UnitTesting;
using Generators;

namespace Generators.Tests
{
    [TestClass]
    public class DoubleGeneratorTest
    {
        [TestMethod]
        public void GetValueTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}