using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestsGenerator.Test
{
    [TestClass]
    public class GeneratorTest
    {
        [TestMethod]
        public void GenerateTestClassesTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}