using Microsoft.VisualStudio.TestTools.UnitTesting;
using TestsGenerator;

namespace TestsGenerator.Tests
{
    [TestClass]
    public class ReaderTest
    {
        [TestMethod]
        public void ReadFromFilesTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}